tasks:
        default:
                onboard_world: MessengerBotChatOnboardWorld
                task_world: MessengerBotChatTaskWorld
                timeout: 1800
                agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 3000
opt:
        debug: True
        models:
                blenderbot2_400M:
                        model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
                        model_file: zoo:blenderbot2/blenderbot2_400M/model
                        interactive_mode: True
                        no_cuda: False
                        override:
                                search_server: 0.0.0.0:10002
                                query_generator_truncate: 256
                                label_truncate: 128
                                text_truncate: 256
                                truncate: 256
                                model_parallel: true
