tasks:
        default:
                onboard_world: MessengerBotChatOnboardWorld
                task_world: MessengerBotChatTaskWorld
                timeout: 18000
                agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 300000
opt:
        debug: False
        models:
                blenderbot2_400M:
                        model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
                        model_file: models:blenderbot2/blenderbot2_400M/model
                        interactive_mode: True
                        no_cuda: False
                        override:
                                knowledge_access_method: memory_only
                                search_server: None
                                query_generator_truncate: 256
                                label_truncate: 128
                                text_truncate: 256
                                truncate: 256
